### ISSUE TITLE
Close tasks automatically with deadline setting

### ISSUE THREAD

**Issue by kierio04** [crackhex/TAS-Comp-Bot-py#15]
- [x] Add a new argument to the `/start-task` command for the deadline, using UNIX time
- [x] The task automatically stops when the deadline is reached

**Comment by Dash-QC** [comment]
Done with EXTRA in https://github.com/crackhex/TAS-Comp-Bot-py/commit/4859f3e28c4f7a1b5b5c54968aa987f2f939681b:

Deadline is an optional argument (in the case we still want to stop the task ourselves manually, or for testing purposes.)

After the task is created (whether with a deadline or not), you may use $/set-deadline to set a deadline if you hadn't, or to extend/shorten the task.
