### ISSUE TITLE
Removing leader system (and other stuff related to teams)

### ISSUE THREAD

**Issue by shxd10** [crackhex/TAS-Comp-Bot-py#2]
### Unless there’s something internally making it impossible to work without it, I don’t see the need for a leader, especially if you’re going to limit permissions for other team commands to just the leader

- All people being able to submit is expected (the old bot did this), however again I don’t see the need to submit on behalf of the leader If you have to give each submission a user ID, are you not able to have an array of lists of team members instead? (This is where utilising submission numbers is incredibly useful) (As far as I’m aware, the old bot didn’t use any leader system, and it worked fine — this is why I wanted someone to look into what was done before, even if the code wasn’t written well)
- Each team member should be able to change the team name
- There should be a $setteamname command, as $setname should only apply to the name of the person using it. Setting your team name should automatically format your submission name in the TeamName (Person1 & Person2) format, rather than having to format it like that when using the command, with $setname only affecting the Person1 and Person2
- I don’t think there should be a command to completely dissolve a team, just for an individual person to leave (allowing for the remaining team member(s) to continue with their submission)

_Message by kierio_

**Comment by kierio04** [comment]
Covered by 8580906, 8031d71, f32e4e0, d102c27
