### ISSUE TITLE
Adding partners to existing teams

### ISSUE THREAD

**Issue by kierio04** [crackhex/TAS-Comp-Bot-py#5]
- [x] When the $collab command is used by someone already in a team, it adds the new invitee to the existing team
- [x] Before the this happens, a confirmation message with "Yes" and "No" buttons should be sent, saying 
> WARNING: You are already in a team. This will add `@<invitee>` to your team. To instead create a new team, use either `$leaveteam` or `$dissolve` first.
> 
> Are you sure you want to continue?

NOTE: So long as #4 is adhered to, no additional bugs should arise as a result of introducing a live invitation to an existing team.

**Comment by Dash-QC** [comment]
Addressed in https://github.com/crackhex/TAS-Comp-Bot-py/commit/0bf2b4088f0980ee82a5b5892e1107a2d66cc60b
