### ISSUE TITLE
Invalid invites not being resolved

### ISSUE THREAD

**Issue by kierio04** [crackhex/TAS-Comp-Bot-py#7]
When you use the `$collab` function with an invalid invitee argument, the bot doesn't resolve the pending collaboration, and so you can't send a real invite.

**Mock scenario:**

kierio04: `$collab \@DashQC`
TASCompBot: (no response)
kierio04: `$collab @DashQC`
TASCompBot: `You already have a pending collaboration request. Please wait for it to be resolved.`

**Comment by Dash-QC** [comment]
Fixed in 648c940.
